// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddStation(arg1:string,arg2:main.Station):Promise<void>;

export function BuiltinPlaylistName():Promise<string>;

export function ClearHistory():Promise<void>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DeleteRecording(arg1:string):Promise<void>;

export function ExportRecording(arg1:string):Promise<string>;

export function FavoriteStations():Promise<Array<main.FavStation>>;

export function FavoriteURLs():Promise<Array<string>>;

export function FindStation(arg1:string):Promise<Array<string>>;

export function FullscreenWindowOff():Promise<void>;

export function FullscreenWindowOn():Promise<void>;

export function GetStations(arg1:string):Promise<Array<main.Station>>;

export function HideWindow():Promise<void>;

export function InsertStation(arg1:string,arg2:number,arg3:main.Station):Promise<void>;

export function IptvCategories():Promise<Array<string>>;

export function ListPlaylists():Promise<Array<main.PlaylistInfo>>;

export function ListRecordings():Promise<Array<main.RecordingInfo>>;

export function MinimiseWindow():Promise<void>;

export function MoveStationCross(arg1:string,arg2:number,arg3:string):Promise<void>;

export function MoveStationTo(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenExternalVlc(arg1:string):Promise<void>;

export function PlayHistory():Promise<Array<main.HistoryEntry>>;

export function PlaylistsDir():Promise<string>;

export function RecordHistory(arg1:string,arg2:string):Promise<void>;

export function RecordingsDir():Promise<string>;

export function RefreshIptv():Promise<void>;

export function RemoveStation(arg1:string,arg2:number):Promise<void>;

export function RenamePlaylist(arg1:string,arg2:string):Promise<void>;

export function ReportError(arg1:string):Promise<void>;

export function SearchChannels(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<main.TvChannel>>;

export function SetVideoRect(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartRecording(arg1:main.Station):Promise<main.RecordingInfo>;

export function StopRecording(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:main.Station):Promise<boolean>;

export function ToggleMaximiseWindow():Promise<void>;

export function UpdateStation(arg1:string,arg2:number,arg3:main.Station):Promise<void>;

export function VlcAvailable():Promise<boolean>;

export function VlcEmbeddedAvailable():Promise<boolean>;

export function VlcPlay(arg1:string):Promise<void>;

export function VlcSetMute(arg1:boolean):Promise<void>;

export function VlcSetPaused(arg1:boolean):Promise<void>;

export function VlcSetVolume(arg1:number):Promise<void>;

export function VlcState():Promise<string>;

export function VlcStop():Promise<void>;
