// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStation(arg1, arg2) {
  return window['go']['main']['App']['AddStation'](arg1, arg2);
}

export function BuiltinPlaylistName() {
  return window['go']['main']['App']['BuiltinPlaylistName']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function ExportRecording(arg1) {
  return window['go']['main']['App']['ExportRecording'](arg1);
}

export function FavoriteStations() {
  return window['go']['main']['App']['FavoriteStations']();
}

export function FavoriteURLs() {
  return window['go']['main']['App']['FavoriteURLs']();
}

export function FindStation(arg1) {
  return window['go']['main']['App']['FindStation'](arg1);
}

export function FullscreenWindowOff() {
  return window['go']['main']['App']['FullscreenWindowOff']();
}

export function FullscreenWindowOn() {
  return window['go']['main']['App']['FullscreenWindowOn']();
}

export function GetStations(arg1) {
  return window['go']['main']['App']['GetStations'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InsertStation(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertStation'](arg1, arg2, arg3);
}

export function IptvCategories() {
  return window['go']['main']['App']['IptvCategories']();
}

export function ListPlaylists() {
  return window['go']['main']['App']['ListPlaylists']();
}

export function ListRecordings() {
  return window['go']['main']['App']['ListRecordings']();
}

export function MinimiseWindow() {
  return window['go']['main']['App']['MinimiseWindow']();
}

export function MoveStationCross(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveStationCross'](arg1, arg2, arg3);
}

export function MoveStationTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveStationTo'](arg1, arg2, arg3);
}

export function OpenExternalVlc(arg1) {
  return window['go']['main']['App']['OpenExternalVlc'](arg1);
}

export function PlayHistory() {
  return window['go']['main']['App']['PlayHistory']();
}

export function PlaylistsDir() {
  return window['go']['main']['App']['PlaylistsDir']();
}

export function RecordHistory(arg1, arg2) {
  return window['go']['main']['App']['RecordHistory'](arg1, arg2);
}

export function RecordingsDir() {
  return window['go']['main']['App']['RecordingsDir']();
}

export function RefreshIptv() {
  return window['go']['main']['App']['RefreshIptv']();
}

export function RemoveStation(arg1, arg2) {
  return window['go']['main']['App']['RemoveStation'](arg1, arg2);
}

export function RenamePlaylist(arg1, arg2) {
  return window['go']['main']['App']['RenamePlaylist'](arg1, arg2);
}

export function ReportError(arg1) {
  return window['go']['main']['App']['ReportError'](arg1);
}

export function SearchChannels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchChannels'](arg1, arg2, arg3, arg4);
}

export function SetVideoRect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetVideoRect'](arg1, arg2, arg3, arg4);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['App']['ToggleMaximiseWindow']();
}

export function UpdateStation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStation'](arg1, arg2, arg3);
}

export function VlcAvailable() {
  return window['go']['main']['App']['VlcAvailable']();
}

export function VlcEmbeddedAvailable() {
  return window['go']['main']['App']['VlcEmbeddedAvailable']();
}

export function VlcPlay(arg1) {
  return window['go']['main']['App']['VlcPlay'](arg1);
}

export function VlcSetMute(arg1) {
  return window['go']['main']['App']['VlcSetMute'](arg1);
}

export function VlcSetPaused(arg1) {
  return window['go']['main']['App']['VlcSetPaused'](arg1);
}

export function VlcSetVolume(arg1) {
  return window['go']['main']['App']['VlcSetVolume'](arg1);
}

export function VlcState() {
  return window['go']['main']['App']['VlcState']();
}

export function VlcStop() {
  return window['go']['main']['App']['VlcStop']();
}
